@baseUrl =  http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

###Recados
###List de Todos Recados 
###
GET {{baseUrl}}/recados
?limit=5
?offset=0
Authorization: Bearer {{authToken}}

###Lista de um Recados 
GET {{baseUrl}}/recados//

###criar  um Recados 
POST {{baseUrl}}/recados
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "texto": "Recado de teste4",
  "paraId": 12
} 

###Atualiza de um Recados 
PATCH {{baseUrl}}/recados/2 
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "texto": "Recado Atualizado",
  "paraId": 6,
  "lido": true
}

###Deleta um Recados
DELETE {{baseUrl}}/recados/5
Authorization: Bearer {{authToken}}

#

# Pessoa

###List de todas as pessoas 
###
GET {{baseUrl}}/pessoas/
?limit=10
?offset=0
Authorization: Bearer {{authToken}}
###Lista de um pessoas 
GET {{baseUrl}}/pessoas/2/
###Criar de um pessoas 
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "email": "teste@example.com",
  "password": "123456",
  "nome": "Marlon Machado"
  
} 
###Atualização de um pessoas 
PATCH  {{baseUrl}}/pessoas/4
Content-Type: application/json

{
  "nome ": "aaaaaaaa"
} 
###Deleta um Recados
DELETE {{baseUrl}}/pessoas/5

#

# Auth
### Autenticação
# @name authenticate

POST  {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "testedeusuario1@email.com",
  "password": "123456"
  
} 


### Re-Autenticação
# @name reAuthenticate

POST  {{baseUrl}}/auth/refresh/
Content-Type: application/json

{
  "refreshToken":"{{refreshToken}}"
  
} 